FROM quay.io/fenicsproject/stable:current
MAINTAINER Maximilian Metti, Arthur Bousquet


RUN pip install jupyter

WORKDIR /home/work/

# ENTRYPOINT pip install --upgrade -r requirements.txt --prefix=/usr/local && /bin/bash
